// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmmNQm_YFW5W_C7cD65u9-kXM5Lq2Nco',
    appId: '1:298903489962:web:33a792b8118bf430606fd3',
    messagingSenderId: '298903489962',
    projectId: 'dennys-app',
    authDomain: 'dennys-app.firebaseapp.com',
    storageBucket: 'dennys-app.appspot.com',
    measurementId: 'G-1J6SCMYZFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9F6yr7xdDedPVY5F8t8A-591vTvW0FdI',
    appId: '1:298903489962:android:bd34aeda851448f2606fd3',
    messagingSenderId: '298903489962',
    projectId: 'dennys-app',
    storageBucket: 'dennys-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKT2Q5KoGrXh1E_BnWPXG3kmAoq-69VZM',
    appId: '1:298903489962:ios:9ef3a175a656b9f7606fd3',
    messagingSenderId: '298903489962',
    projectId: 'dennys-app',
    storageBucket: 'dennys-app.appspot.com',
    iosClientId: '298903489962-keba2c7mp2o2eji7b14faanom6o7pgv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dennysWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKT2Q5KoGrXh1E_BnWPXG3kmAoq-69VZM',
    appId: '1:298903489962:ios:9ef3a175a656b9f7606fd3',
    messagingSenderId: '298903489962',
    projectId: 'dennys-app',
    storageBucket: 'dennys-app.appspot.com',
    iosClientId: '298903489962-keba2c7mp2o2eji7b14faanom6o7pgv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dennysWebApp',
  );
}
